// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppgxbfjlhlrwbvsqqalx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ3hiZmpsaGxyd2J2c3FxYWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTIxMjUsImV4cCI6MjA3MDE2ODEyNX0.ZZeLk5yHu-7Q_ktJiAFl0bb20bQpvAatL5xY7aSte4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});